- src/components/Login/LoginFooter.tsx
- src/components/Login/LoginHome.tsx
- src/components/Welcome/WelcomeFooter.tsx
- src/components/Welcome/WelcomeHome.tsx
- src/pages/Welcome/WelcomePage.tsx
- src/styles/style.d.ts
- src/styles/theme.ts
resolved #19 
- LoginPage와 구조가 거의 같기 때문에, 복잡한 코드는 없습니다!
- 가볍게 한 번 봐주시면 될 것 같아요!
> [WelcomePage] WelcomePage 퍼블리싱

- src/components/MainPage/SideMenu.tsx
- src/components/MainPage/SideMenuUserInfo.tsx
- src/pages/MainPage.tsx
resolved #11 
```tsx
const SideMenuUserInfo = ({ isLogin }: { isLogin: boolean }) => {
const point = 2000;
return isLogin ? (
<St.SideMenuUserInfoSection>
<St.SideMenuUserName>
김희진
<div>님</div>
</St.SideMenuUserName>
<St.SideMenuUserPointWrapper>
<St.SideMenuUserPointTitle>보유 포인트</St.SideMenuUserPointTitle>
<St.SideMenuUserPointTextWrapper>
<St.SideMenuUserPoint>{point.toLocaleString()}</St.SideMenuUserPoint>
<div>P</div>
</St.SideMenuUserPointTextWrapper>
<St.SideMenuUserPointChargeButton>충전하기</St.SideMenuUserPointChargeButton>
</St.SideMenuUserPointWrapper>
</St.SideMenuUserInfoSection>
) : (
<St.SideMenuAnonymousSection>
<St.SideMenuLoginButton>
<St.SideMenuAnoymousTitle>로그인이 필요합니다</St.SideMenuAnoymousTitle>
<IcArrowRightLight />
</St.SideMenuLoginButton>
</St.SideMenuAnonymousSection> …
```
> [MainPage] SideBar UI 구현

- src/components/Order/RefundInfo.tsx
- src/pages/Login/OrderPage.tsx
resolved #40 
- 그냥 뷰 짠거예용 
https://github.com/TEAM-TATTOUR/tattour-client/assets/81505421/14c7811c-b59a-41f7-a4f5-7c0cd042de9f
> Order page/#40 re fund component publishing

- src/components/Header.tsx
- src/components/MainPage/HotCustom.tsx
- src/components/MainPage/MainBanner.tsx
- src/components/MainPage/MainFooter.tsx
- src/components/MainPage/MainHeaderButton.tsx
- src/components/MainPage/MainTheme.tsx
- src/components/MainPage/SideMenu.tsx
- src/pages/MainPage.tsx
resolved #10
```tsx
const MainPage = () => {
const [isHeaderTransparent, setIsHeaderTransparent] = useState(true);
const [isSideMenuOpen, setIsSideMenuOpen] = useState(false);
const [isFooterVisible, setIsFooterVisible] = useState(false);
const debouncedHandleScroll = throttle(handleScroll, 100);
window.addEventListener('scroll', debouncedHandleScroll, { passive: true });
return () => {
window.removeEventListener('scroll', debouncedHandleScroll); //clean up
};
}, []);
const handleScroll = () => {
const scrollY = window.scrollY;
setIsHeaderTransparent(scrollY === 0);
// image 사이즈나오면 변경 예정
setIsFooterVisible(scrollY > 500);
};
const reanderMainPageHeader = () => {
return (
<Header
transparent={isHeaderTransparent}
leftSection={isHeaderTransparent ? <ImgLogoLight /> : …
```
> [Main page] 메인 페이지 이벤트 적용

- src/components/Register/RegisterPhoneNumForm.tsx
> fix: props 문법 제대로 적용되지 않은 이슈 해결

- src/common/HotCustom.tsx
- src/common/MainHeaderButton.tsx
- src/common/SideMenu.tsx
- src/common/SideMenuUserInfo.tsx
resolved #144 
Hot Custom, SideMenu Common으로 변경.
SideMenu를 사용하기 위해선 isSIdeMenuOpen state를 각 페이지에서 써야 함.
> feat: HotCustom, SideMenu 분리

- package.json
- src/Router.tsx
- src/components/Custom/NoDesign/CustomRequset.tsx
- src/pages/Custom/NoDesign/CustomRequestPage.tsx
resolved #21 
<br/>
<br/>
```ts
//글자 수 세기 관련 state
const [nameInputCount, setNameInputCount] = useState(0);
const [etcTextAreaCount, setEtcTextAreaCount] = useState(0);
const handleChangeNameInput = (e: React.ChangeEvent<HTMLInputElement>) => {
//value가 없을 때 0으로 글자 수 세지도록
if (e.target.value === '') setNameInputCount(0);
const lengthCount = limitMaxLength(e, MAX_NAME_COUNT);
if (!lengthCount) return;
setNameInputCount(lengthCount);
};
...
const handleChangeEtcTextArea = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
if (e.target.value === '') setEtcTextAreaCount(0);
const lengthCount = limitMaxLength(e, MAX_ETC_COUNT);
if (!lengthCount) return;
setEtcTextAreaCount(lengthCount);
};
```
* 백스페이스로 글자를 다 지웠을 때 1로 계속 이전 값을 가지고 있는 오류가 있어 초기에 value의 값이 없으면 카운팅을 0으로 할 수 있도록 설정
```ts
// 이모티콘을 한 …
```
> [CustomRequestPage] 이미 그려둔 도안이 있는 경우 주제 및 추가 요청사항 입력

- src/Router.tsx
- src/components/PointCharge/Charge.tsx
- src/pages/PointCharge/ChargePage.tsx
resolved #44
댠순 퍼블리싱입니당 가볍게 봐주세용~
input 값 검증 (1000원 단위인지)은 다음 이슈에서 진행할 예정이고
input에 값을 입력했을 때 '원' 단위는 디자인 논의 후 다음 이슈에서 적용할 예정입니당
x
> [ChargePage] 포인트 충전 뷰(단순 UI) 구현

- src/common/Modal/WelcomeModal/WelcomeModal.tsx
- src/common/Modal/WelcomeModal/WelcomeModalForm.tsx
resolved #134 
- 기존 모달과 비슷하게 구현했고, 쿠폰은 이미지로 넣었기 때문에 크게 리뷰할 부분 없을 것 같습니다.
- 이상한 부분 없는지만 확인해주시면 감사용
https://github.com/TEAM-TATTOUR/tattour-client/assets/80264647/d4353a0e-51ef-4271-813d-cbec004d804f
> [Common] 가입 축하 모달

- package.json
- src/components/PointCharge/AccountCopy.tsx
- yarn.lock
resolved #50
```ts
const handleCopyClipboard = () => {
alert('계좌번호가 복사되었습니다.');
};
...
<CopyToClipboard onCopy={handleCopyClipboard} text={ACCOUNT_INFO}>
<St.AccountBox>
<St.AccountBoxNum>{ACCOUNT_INFO}&nbsp;(손*진)</St.AccountBoxNum>
<St.AccountBoxCopy>복사하기</St.AccountBoxCopy>
</St.AccountBox>
</CopyToClipboard>
```
x
https://github.com/TEAM-TATTOUR/tattour-client/assets/77691829/d675a749-890b-4293-a6ad-13c2acb3e152
> [TransferPage] 계좌번호 복사하기 기능 구현

- src/Router.tsx
- src/components/Detail/DetailInfo.tsx
- src/pages/DetailPage.tsx
- src/styles/theme.ts
> [Detail page] 캐러셀과 하단 리스트 제외하고 퍼블리싱

- src/components/Detail/DetailFooter.tsx
- src/pages/DetailPage.tsx
resolved #33 
- PageLayout으로 헤더 푸터 다 넣어줬고 
- 좋아요 토글 구현했어용 
https://github.com/TEAM-TATTOUR/tattour-client/assets/81505421/68d4d1b1-11d2-495e-a827-fda43557dd12
> Detail page/#33 page layout wrap

- src/common/ToastMessage/Toast.tsx
- src/components/Register/RegisterPhoneNumForm.tsx
> Merge Feature/toast page to develop

- src/components/Detail/DetailCarousel.tsx
- src/components/Detail/DetailInfo.tsx
- src/pages/DetailPage.tsx
resolved #32 
- preTask 했던지라 부담없이 했습니다. 
- 추후 CUSTOM 라벨을 붙일때 어떻게 해야할지는 고민해볼 예정 
https://github.com/TEAM-TATTOUR/tattour-client/assets/81505421/b15abda5-0a6a-437d-92ef-11ec30cb830a
> [DetailPage] 상단의 carousel구현

- src/Router.tsx
- src/assets/icon/ic_search_gray.svg
- src/assets/icon/index.ts
- src/components/Search/SearchInputForm.tsx
- src/components/Search/SearchResult.tsx
- src/components/Search/SearchResultItem.tsx
- src/pages/Search/SearchPage.tsx
- src/pages/Search/SearchResultPage.tsx
resolved #15 
```
const SearchPage = () => {
return (
<PageLayout>
<SearchInputForm />
<Outlet />
</PageLayout>
);
};
export default SearchPage;
```
outlet을 사용하여 검색 기능 구현.
```
const SearchInputForm = () => {
const inputRef = useRef<HTMLInputElement>(null);
const handleClickBackButton = () => {
navigate('/');
};
const handleSubmitSearchForm = () => {
navigate(`/search/${inputRef.current?.value}`);
};
return (
<St.SearchFormWrapper>
<IcArrowLeftGray onClick={handleClickBackButton} />
<St.SearchForm>
<St.SearchInput ref={inputRef} placeholder={'검색어를 입력해주세요.'} />
<IcSearchGray onClick={handleSubmitSearchForm} />
</St.SearchForm>
</St.SearchFormWrapper>
);
};
```
검색 버튼을 눌러 :keyword 전달.
> Search page/#15 searchpage UI

- src/components/Header.tsx
- src/components/PointCharge/AccountCopy.tsx
- src/components/PointCharge/PointTransferFooter.tsx
- src/components/PointCharge/TransferMain.tsx
- src/components/PointCharge/TransferPolicy.tsx
- src/pages/pointCharge/TransferPage.tsx
resolved #182 
```ts
const TransferPage = () => {
const [isActiveNext, setIsActiveNext] = useState(false);
const renderTransferPageHeader = () => {
return (
<Header
leftSection={<BackBtn />}
title='포인트 충전'
rightSection={<CancelBtn />}
progressBar={<ProgressBar curStep={2} maxStep={2} />}
/>
);
};
return (
<PageLayout
renderHeader={renderTransferPageHeader}
footer={<PointTransferFooter isActiveNext={isActiveNext} />}
>
<TransferMain />
<TransferPolicy setIsActiveNext={setIsActiveNext} />
</PageLayout>
);
};
```
```ts
const handleClickAgreeCheckBox = (e: React.ChangeEvent<HTMLInputElement>) => {
e.target.checked ? setIsActiveNext(true) : setIsActiveNext(false);
};
```
- x
https://github.com/TEAM-TATTOUR/tattour-client/assets/77691829/5b947bef-acce-4eb5-a746-6cdaae5e7f4c
> [TransferPage] 송금 페이지 

- src/components/Header.tsx
- src/components/Register/InputCertificationForm.tsx
- src/components/Welcome/WelcomeFooter.tsx
- src/components/Welcome/WelcomeHome.tsx
- src/pages/Welcome/WelcomePage.tsx
resolved #167 
- div 삭제 후  St.HeaderWrapper에 ProgressBar까지 한 번에 묶어줌
```
<St.header transparent={transparent} $fixed={fixed}>
<St.SectionWrapper>
{leftSection}
{title && <St.title>{title}</St.title>}
{rightSection}
</St.SectionWrapper>
{progressBar}
</St.header>
```
- 모바일에서 스크롤 생기는 이슈 아직 해결 못함
> [WelcomePage] 헤더 붙이기

- src/components/Header.tsx
resolved #이슈 없음ㅋㅋ
header의 taransparent가 $가 prefix로 빠져있고 non-boolean타입으로 styled-component로 설정이 안되어 있는 이슈
> fix: header 에러 수정

- src/common/Footer/NextFooter.tsx
> feat : 다음 버튼 푸터 추상화 구현

- src/components/Custom/HaveDesign/CustomTheme.tsx
- src/components/Custom/HaveDesign/CustomThemeFooter.tsx
- src/pages/Custom/HaveDesign/CustomThemePage.tsx
resolved #78 
-  연서랑 뷰 겹쳐서 프로그레스바 정도만 추가했습니다!
> [CustomThemePage] 주제 및 설명 입력 뷰 구현

- src/components/Custom/HaveDesign/AdditionalRequest.tsx
- src/components/Custom/HaveDesign/AdditionalRequestFooter.tsx
- src/pages/Custom/HaveDesign/AdditionalRequestPage.tsx
> [AdditionalRequestPage] 추가 요청 사항 화면 구현

- src/components/MainPage/SideMenuUserInfo.tsx
> MainPage -> develop 병합

- src/common/SideMenu.tsx
> feat: sideMenu 스크롤 방지 useEffect화

- src/pages/pointCharge/TransferPage.tsx
resolved #182
- 모달 안넣은거 추가
- x
https://github.com/TEAM-TATTOUR/tattour-client/assets/77691829/4a9c6991-05f4-4550-b5d3-69a8a288ea9a
> [TransferPage] 헤더 x 버튼에 사용자 이탈 모달 뜨도록 추가

- src/components/List/FilterBottom.tsx
- src/components/List/TattooList.tsx
- src/pages/ListPage.tsx
> ListPage 필터링 문제 해결용 test 브랜치 

- src/components/Custom/HaveDesign/ReceiptDetail.tsx
- src/components/Custom/HaveDesign/ReceiptFooter.tsx
- src/components/Custom/HaveDesign/Submitted.tsx
- src/pages/Custom/HaveDesign/ReceiptPage.tsx
resolved #189 
resolved #84 
develop으로 머지합니다!
- 기타 자잘한 UI 수정이나 버튼 기능 수정 등은 나중에 한 번에 적용할게요..!
> [ReceiptPage] Develop으로 Feature/ReceiptPage 머지 진행

- src/components/Order/OrderFooter.tsx
- src/pages/OrderPage.tsx
resolved #229 
- 무난하게 navigation 붙였는데 전달할 props가 정확하지 않는 것들이 있어서 주석으로 남겨놨어용
> Order page/#229 navigation

- src/components/Welcome/WelcomeFooter.tsx
- src/components/Welcome/WelcomeHome.tsx
resolved #247 
- 스타일 요소 반영했습니다.
- 마진, position 변경
> [WelcomPage] 스타일 요소 반영

- src/components/PointCharge/AccountCopy.tsx
- src/components/PointCharge/PointTransferFooter.tsx
- src/components/PointCharge/TransferMain.tsx
- src/components/PointCharge/TransferPolicy.tsx
- src/pages/pointCharge/TransferPage.tsx
> TransferPage => develop 머지

- src/Router.tsx
- src/components/Complete/CompleteFooter.tsx
- src/components/Order/PaymentInfo.tsx
- src/components/Order/PaymentMini.tsx
- src/components/Order/ProductInfo.tsx
- src/pages/Order/CompletePage.tsx
- src/pages/Order/OrderPage.tsx
resolved #237 
- 재사용 가능한거 다 뽑음 
https://github.com/TEAM-TATTOUR/tattour-client/assets/81505421/7171f2b2-acd6-4798-9c36-574a74c6dc45
> [Complete page] 완료 페이지 싹다 구현 

- src/Router.tsx
> feature: 라우터 수정하기

- src/components/Custom/HaveDesign/AdditionalRequest.tsx
- src/pages/Custom/HaveDesign/AdditionalRequestPage.tsx
resolved #254 
-  조건부 버튼 활성화
- 디자인 수정사항 반영
- 미사용 스타일 삭제
- x
https://github.com/TEAM-TATTOUR/tattour-client/assets/92876819/1af87afd-2639-420f-bace-258b1abfa14e
> [AdditionalRequestPage] 버튼 조건부 활성화 적용 및 디자인 수정사항 반영

- src/common/Modal/CheckModal/CheckModalForm.tsx
resolved #302 
- 사파리에서 flex 속성 안 먹는 이슈 해결
```
-webkit-flex: 1; /* Safari 6.1+ */
-ms-flex: 1; /* IE 10 */
flex: 1;
```
> [CommonPage] 사파리에서 flex 속성 안 먹는 이슈 해결

- src/common/Modal/TempSaveModal/TempSaveModal.tsx
- src/components/Custom/Common/OnBoardingCarousel.tsx
resolved #301
- 디자인 요청사항 반영,
- 모달 색 수정
- x
> [OnBoardingPage] 캐러셀 마진 수정, 모달 수정

- .gitignore
- src/common/Modal/CheckModal/CheckModal.tsx
- src/common/Modal/CheckModal/CheckModalForm.tsx
- src/components/PointCharge/Charge.tsx
- src/components/PointCharge/PointChargeFooter.tsx
- src/components/PointCharge/PointTransferFooter.tsx
- src/components/PointCharge/TransferMain.tsx
- src/page/PointCharge/ChargePage.tsx
- src/page/PointCharge/TransferPage.tsx
resolved #314 
```ts
const handleClickContinueBtn = async () => {
//포인트 충전
try {
await api.post('/user/point/charge', {
chargeAmount: chargeAmount,
});
onClose();
navigate(redirectURL);
} catch (err) {
console.log(err); //추후 삭제 예정(에러 페이지 라우팅 하면)
// navigate("/error")
}
};
```
* 커스텀 훅 안 쓴 이유 : 핸들러 함수 내에서 post 통신이 이루어져야 하는데 커스텀 훅은 컴포넌트 함수 바로 밑 body에서만 호출 가능하므로 올바른 방식이 아닌듯 해서 바로 통신했습니다 조언 부탁!
- x
https://github.com/TEAM-TATTOUR/tattour-client/assets/77691829/83164dea-9ec1-4917-99df-46988ab9988c
> [TransferPage] 포인트 충전 POST API

- src/components/List/FilterBottom.tsx
- src/components/List/TattooList.tsx
- src/libs/hooks/list/useGetAllList.tsx
- src/libs/hooks/list/useGetGenre.tsx
- src/libs/hooks/list/useGetStyle.tsx
- src/libs/hooks/useGetAllList.tsx
> List page/#287 api

- src/common/Footer/NextFooter.tsx
- src/types/customInfo.ts
> feature: custom에서 쓰이는 NextFooter 수정 및 types 수정

- src/common/Footer/NextFooter.tsx
- src/types/customInfo.ts
> [Common] NextFooter 수정 및 types 수정

- src/common/Footer/NextFooter.tsx
- src/types/customInfo.ts
resolved #83 
- PATCH 훅 파일 생성
- x
> [Common]custom에서 쓰는 Patch에 쓰일 request interface type 수정

- src/common/Footer/NextFooter.tsx
> [Common]types 변경에 따른 푸터 내용 수정

- src/components/MyTattoo/MyLike.tsx
- src/libs/hooks/useGetLikeSticker.ts
resolved #336 
```
import { AxiosError } from "axios";
import api from "../api";
import { useState, useEffect } from "react";
export interface LikeStickerProps {
id: number;
name: string;
price: number;
discountRate: number;
discountPrice: number;
mainImageUrl: string;
}
interface LikeStickerResponse {
data: {
stickersliked: LikeStickerProps[];
};
code: number;
message: string;
}
const useGetLikeSticker = () => {
const [response, setResponse] = useState<LikeStickerProps[]>([]);
const [error, setError] = useState<AxiosError>();
const [loading, setLoading] = useState(true);
const fetchData = async () => {
await api.get('/user/product-liked/saved')
.then(res => {
const data: LikeStickerResponse = res.data;
setResponse(data.data.stickersliked);
})
.catch(err => {
setError(err);
})
.finally(() …
```
> [My Tattoo] 내 타투 like api 연결

- src/page/Custom/HaveDesign/AdditionalRequestPage.tsx
- src/page/Custom/HaveDesign/CustomThemePage.tsx
- src/page/Custom/HaveDesign/SelectKeywordPage.tsx
- src/page/Custom/HaveDesign/StylingColorPage.tsx
- src/page/Custom/NoDesign/CustomImgPage.tsx
- src/page/Custom/NoDesign/CustomRequestPage.tsx
- src/page/Custom/PricePage.tsx
- src/page/CustomReference/CustomReferencePage.tsx
resolved #329
```ts
const location = useLocation();
<Header
leftSection={<IcBackDark onClick={() => navigate('/select-keyword')} />}
//navigate 될 url 넣어주기
...
```
- x
> [Custom] back navigate 수정

- src/page/Custom/HaveDesign/AdditionalRequestPage.tsx
- src/page/Custom/HaveDesign/CustomThemePage.tsx
- src/page/Custom/HaveDesign/SelectKeywordPage.tsx
- src/page/Custom/HaveDesign/StylingColorPage.tsx
- src/page/Custom/NoDesign/CustomImgPage.tsx
- src/page/Custom/NoDesign/CustomRequestPage.tsx
- src/page/Custom/PricePage.tsx
- src/page/CustomReference/CustomReferencePage.tsx
> Feature/custom -> develop

- src/common/SideMenuUserInfo.tsx
> feat: 로그인 버튼 navigate 연결

- src/common/Footer/NextFooter.tsx
- src/page/CustomReference/CustomReferencePage.tsx
- src/types/customInfo.ts
> [Common]타입 수정 및 푸터 수정

- src/common/Footer/NextFooter.tsx
- src/types/customInfoType.ts
- customInfo 변수랑 customInfo 타입이랑 이름이 같아서 에러 떠서 타입 이름 바꿨습니다~!
> [Common] chore: 타입 이름 바꿈

- src/common/Footer/NextFooter.tsx
- src/types/customInfoType.ts
> [Common] type 업데이트

- src/common/HotCustom.tsx
- src/page/ListPage.tsx
- src/page/MainPage.tsx
> fix: detail 페이지 네비게이션 수정

- src/common/Modal/EscapeModal/CustomSizeEscapeModal.tsx
- src/common/Modal/EscapeModal/EscapeModalForm.tsx
- src/common/Modal/TempSaveModal/TempSaveModal.tsx
resolved #377 
- 커스텀 신청 이탈 모달 라이팅 수정
- 임시저장 모달 navigate 수정
- x
> [Common] 커스텀 신청 이탈 모달 라이팅 수정

- src/common/Modal/ChargePointModal/ChargePointModal.tsx
- src/components/Custom/Common/SelectCustomFooter.tsx
resolved #389 
유저 프로필에서 포인트 정보 가져오기
> [SelectPage] 유저 프로필에서 포인트 정보 가져오기

- src/components/Custom/Common/OnBoardingFooter.tsx
- src/libs/hooks/useGetCustomSaveList.ts
- src/libs/hooks/useKakaoLogin.tsx
> [OnBoardingPage] 임시 저장된 데이터가 없으면 바로 select 페이지로 navigate 되도록 수정

- src/libs/hooks/detail/useGetSticker.tsx
> fix: 디테일 페이지 리렌더링 문제 해결

- README.md
> Update README.md : 핵심 기능 추가

- src/common/Modal/ChargePointModal/ChargePointCompleteModal.tsx
- src/common/Modal/CheckModal/CheckModal.tsx
- src/common/Modal/CheckModal/CheckModalForm.tsx
- src/common/Modal/EscapeModal/ChargePointEscapeModal.tsx
- src/common/Modal/EscapeModal/EscapeModalForm.tsx
- src/components/PointCharge/PointTransferFooter.tsx
- src/page/PointCharge/ChargePage.tsx
- src/page/PointCharge/TransferPage.tsx
resolved #412
- 포인트 충전 충전 완료 및 redirect URL로 escape 하도록 추가
- x
> [Common] 포인트 충전 충전 완료 및 redirect URL로 escape 하도록 추가

- src/components/Custom/Common/OnBoardingFooter.tsx
- src/components/MainPage/MainBanner.tsx
- src/page/Custom/Common/OnBoardingPage.tsx
> Refactor page/#421 apply qa

- src/components/Custom/Common/OnBoardingFooter.tsx
- src/components/MainPage/MainBanner.tsx
- src/page/Custom/Common/OnBoardingPage.tsx
> Merge Feature/refactor page to develop

- src/common/HotCustom.tsx
- src/page/ListPage.tsx
- src/page/MainPage.tsx
resolved #420 
- 공통 컴포넌트 HOT CUSTOM 수정해서 
- Main Page랑 
- List Page 각각 조건부 렌더링 했습니다
> [List Page] HOT CUSTOM 옆 화살표 조건부 렌더링

- src/common/CustomScrollContainer.tsx
- src/components/Detail/DetailFooter.tsx
- src/components/Detail/DetailInfo.tsx
> Detail page/#422 qa

- src/components/Search/SearchInputForm.tsx
- src/components/Search/SearchResult.tsx
> fix: image keyword

- src/common/Footer/NextFooter.tsx
- src/components/Custom/NoDesgin/CustomImg.tsx
- src/components/Custom/NoDesgin/CustomImgAttach.tsx
- src/page/Custom/Common/CustomSizePage.tsx
- src/page/Custom/NoDesign/CustomImgPage.tsx
- src/page/Custom/NoDesign/CustomRequestPage.tsx
- src/page/Custom/PricePage.tsx
> feat : mainimageUrl 빼기

- src/common/HotCustom.tsx
- src/components/MyTattoo/MyCustom.tsx
- src/components/MyTattoo/MySaveItem.tsx
- src/components/MyTattoo/MyTattooDetailSection.tsx
- src/components/MyTattoo/MyTattooTagSection.tsx
- src/components/Search/SearchInputForm.tsx
- src/components/Search/SearchResult.tsx
- src/components/Search/SearchResultItem.tsx
- src/libs/hooks/useGetCustomDetail.ts
- src/page/ListPage.tsx
- src/page/MyTattooDetail.tsx
> fix: build 에러 수정

- src/Router.tsx
- src/components/Custom/HaveDesign/Canvas.tsx
- src/components/Custom/HaveDesign/CustomImageAttach.tsx
- src/components/Custom/HaveDesign/CustomReference.tsx
- src/components/Custom/HaveDesign/HaveDesignFooter.tsx
- src/components/Custom/HaveDesign/PaintBottomSheet.tsx
- src/components/Custom/HaveDesign/ReceiptDetail.tsx
- src/components/Custom/HaveDesign/SelectColor.tsx
- src/page/Custom/Common/CustomSizePage.tsx
- src/page/Custom/HaveDesign/AdditionalRequestPage.tsx
- src/page/Custom/HaveDesign/CustomReferencePage.tsx
- src/page/Custom/HaveDesign/CustomThemePage.tsx
- src/page/Custom/HaveDesign/HaveDesignCustomPage.tsx
- src/page/Custom/HaveDesign/ReceiptPage.tsx
- src/page/Custom/HaveDesign/SelectKeywordPage.tsx
- src/page/Custom/HaveDesign/StylingColorPage.tsx
- src/page/Custom/PricePage.tsx
resolved #472 
- HaveDesignCustomPage에 step 변수 값에 따라 switch문을 이용해 다른 페이지를 띄워주도록 페이지 통합을 진행했습니다.
- 통합하는 과정에서 발생하는 에러들이 사이즈 선택 후 통합된 페이지가 아닌 이전 페이지들로 navigate 되는 문제 때문임을 알게 되어서 해결했습니다.
- 폴더구조나 네이밍 수정(`page`->`layout` 등)은 새로 이슈 파서 2차 리팩토링으로 진행할 예정입니다.
에러 내용 : `Uncaught TypeError: Cannot read properties of undefined (reading 'length')`
- 수정 전 코드
```javascript
// 이미지 없으면 다음 비활성화
previewURL.length !== 0 ? setIsActiveNext(true) : setIsActiveNext(false);
}, [previewURL, setIsActiveNext]);
```
여기에서 선택한 이미지가 없으면 `previewURL`이 비어 있어서 undefined에 대한 길이 비교하려고 한다고 에러가 떴고, 이에 대한 예외처리를 이렇게 해주었습니다.🔽
```javascript
if (Array.isArray(previewURL)) {
setIsActiveNext(previewURL.length !== 0);
}
}, [previewURL, setIsActiveNext]);
```
이렇게 `falsy value`가 아닐 때만 length에 접근하도록 해주어서 …
> [haveDesign] haveDesign 페이지 합치기

- src/Router.tsx
- src/common/Modal/ChargePointModal/ChargePointCompleteModal.tsx
- src/common/Modal/ChargePointModal/ChargePointModalForm.tsx
- src/common/Modal/CheckModal/CheckModal.tsx
- src/common/Modal/CheckModal/CheckModalForm.tsx
- src/common/Modal/EscapeModal/ChargePointEscapeModal.tsx
- src/common/Modal/EscapeModal/EscapeModalForm.tsx
- src/common/Modal/EscapeModal/LoginEscapeModal.tsx
- src/common/Modal/WelcomeModal/WelcomeModalForm.tsx
- src/common/PreventAccess/PreventAccess.tsx
- src/common/ToastMessage/Toast.tsx
- src/components/PointCharge/AccountCopy.tsx
- src/components/PointCharge/PointTransferFooter.tsx
- src/components/Register/RegisterPhoneNumForm.tsx
- src/libs/hooks/useKakaoLogin.tsx
> merge Feature/qa rooming into develop

- src/components/Search/SearchInputForm.tsx
- src/components/Search/SearchResult.tsx
- src/components/Search/SearchResultItem.tsx
resolved #501 
폰트 크기 수정 및 카드 간 간격 조절
헤더 마진 수정
> style: 검색 카드 간격 조절 및 폰트 수정

- src/assets/icon/ic_draw.svg
- src/components/Custom/HaveDesign/CustomTheme/CustomTheme.tsx
- src/components/Custom/HaveDesign/Reference/Canvas.tsx
- src/components/Custom/HaveDesign/Reference/ColorPicker.tsx
- src/components/Custom/HaveDesign/Reference/CustomImageAttach.tsx
- src/components/Custom/HaveDesign/Reference/ReferenceInstruction.tsx
- src/components/Custom/HaveDesign/SelectColor/SelectColor.tsx
- src/components/Custom/HaveDesign/SelectKeyword/SelectKeywordInstruction.tsx
> [haveDesign] 캔버스 기능 수정 및 디자인 QA

- src/components/Login/LoginFooter.tsx
- src/components/Login/LoginHome.tsx
- src/components/Register/RegisterName.tsx
- src/components/Register/RegisterNameFooter.tsx
- src/components/Register/RegisterPhoneNum.tsx
- src/components/Register/RegisterPhoneNumForm.tsx
- src/components/Welcome/WelcomeFooter.tsx
- src/components/Welcome/WelcomeHome.tsx
- src/libs/hooks/useKakaoLogin.tsx
- src/page/Login/LoginPage.tsx
Closed #523 
- footer에 `position: fixed`와 `max-width: 43rem`을 줘서 하단 고정 + 화면 크기가 커져도 footer 크기 고정되도록 수정
- header와 내용을 포함하고 있는 컴포넌트 모두 fixed로 처리하여 화면 움직이지 않도록 수정
- 모든 컴포넌트를 fixed로 처리하면서 이슈는 해결함
- position을 계속 여러 번 사용하는 것은 좋지 않다고 생각해서 더 좋은 방향으로 수정할 예정
> [QA] 로그인 CTA 및 화면 상하로 움직이는 이슈 해결

- src/common/Modal/CheckModal/CheckModal.tsx
- src/common/Modal/CheckModal/CheckModalForm.tsx
- src/components/PointCharge/AccountCopy.tsx
- src/components/PointCharge/Charge.tsx
- src/components/PointCharge/PointChargeFooter.tsx
- src/components/PointCharge/PointTransferFooter.tsx
- src/components/PointCharge/TransferMain.tsx
- src/page/MainPage.tsx
> Qa yeonseo/#518 chargepage qa (임시 pr)

- src/common/CustomScrollContainer.tsx
- src/common/MainHeaderButton.tsx
- src/components/Complete/CompleteFooter.tsx
- src/components/Detail/DetailBottom.tsx
- src/components/Detail/DetailFooter.tsx
- src/components/List/TattooList.tsx
- src/components/MainPage/MainFooter.tsx
- src/components/MainPage/MainStyle.tsx
- src/components/Order/OrderFooter.tsx
- src/components/Order/PaymentInfo.tsx
- src/components/Order/PaymentMini.tsx
- src/components/Order/ProductInfo.tsx
- src/components/Order/RefundInfo.tsx
- src/components/Register/RegisterPhoneNumForm.tsx
- src/libs/hooks/detail/useGetPoint.tsx
- src/libs/hooks/detail/useGetRelated.tsx
- src/libs/hooks/detail/useGetSticker.tsx
- src/libs/hooks/list/useGetAllList.tsx
- src/libs/hooks/list/useGetGenre.tsx
- src/libs/hooks/list/useGetStyle.tsx
- src/libs/hooks/order/useGetOrdersheet.tsx
- src/libs/hooks/order/usePostOrder.tsx
- src/page/DetailPage.tsx
- src/page/Order/CompletePage.tsx
- src/page/Order/OrderPage.tsx
resolved #526 
- MainPage Footer도 고정했습니다 
> 셀프로 진행한 2.5차 QA

- src/components/Custom/Common/PriceLayout.tsx
- src/components/Custom/Common/Receipt/ReceiptDetail.tsx
- src/components/Custom/PriceFooter.tsx
> [haveDesign] 추가 QA

- src/components/Custom/HaveDesign/CustomTheme/CustomTheme.tsx
- src/components/Custom/HaveDesign/Reference/CustomImageAttach.tsx
- src/components/Custom/HaveDesign/Reference/CustomReference.tsx
- src/components/Custom/HaveDesign/Reference/ReferenceInstruction.tsx
- src/components/Custom/HaveDesign/SelectColor/SelectColor.tsx
- src/components/Custom/HaveDesign/SelectColor/SelectColorBtn.tsx
- src/components/Custom/PriceHeading.tsx
> [QA] haveDesig QA

- src/components/Custom/HaveDesign/SelectColor/SelectColor.tsx
> [haveDesign] useEffect 로직 분리

- src/common/ToastMessage/Toast.tsx
> Feature/custom => develop (토스트 반영)

- src/components/Custom/HaveDesign/SelectColor/SelectColor.tsx
> Feature/custom => develop (색상 선택 버튼 관련 이슈 수정)

- src/page/MagazinePage.tsx
> fix: build error 해결

- src/components/Custom/HaveDesign/Reference/CustomImageAttach.tsx
> [QA]QA 마저 수정

- src/components/Custom/CountPrice.tsx
- src/components/Custom/PriceFooter.tsx
resolved #558 
- 간단한 문구 수정이라 특별한 내용은 없습니다!
X
> [SP1] 커스텀 price 문구 수정 반영

- src/page/Order/CompletePage.tsx
> [SP1] 결제완료 페이지 UX라이팅 변경사항 수정

- src/libs/api.ts
resolved #598 
- api.ts에 토큰 관련 코드가 모두 정의되어 있었기 때문에, 변경한 부분 거의 없어용
- localStorage -> sessionStorage로 바꾼게 전부입니당
> [ hotfix ] 로컬스토리지 -> 세션스토리지로 변경

- src/page/Login/LoginPage.tsx
resolved #600 
- 프로그래스 바 관련 공통 컴포넌트를 만들어놨기 때문에 숫자만 조금 .. 변경해주었습니다!
- 큰 변경사항 없어용
> [S1] 프로그래스 바 진행도 관련 이슈 해결

- src/components/Cart/CartBottom.tsx
- src/components/Cart/CartItemSection.tsx
> [CartPage] 장바구니 하단 z-index 추가
