TEAM-TATTOUR/tattour-client

- src/components/List/FilterBottom.tsx
- src/components/List/TattooList.tsx
- src/pages/ListPage.tsx
resolved #27 
- `CustomSheet` : 라이브러리 사용과 동시에 커스터마이징 하기 위해 
- 바텀시트 내 모든 항목은 상수배열로 관리하여 mapping 
- 세 종류의 바텀시트를 열고 닫는 state를 상단인 'ListPage'에서 관리함 
- 바텀시트 컴포넌트와 타투리스트 컴포넌트에 state props로 전달 
- 타투 리스트에 있는 필터 버튼 클릭 시 바텀시트 state를 toggle 하기 위해서
- 참고로 바텀시트 내에 항목을 선택하고, 적용하기 누르면 바텀시트 내려가고 해당 항목으로 버튼 형태 바뀌는건 다음 이슈에서 다룰 예정 
- 디코로 노래 듣던거 다 담겻네요 ㅋㅋ 무시부탁
https://github.com/TEAM-TATTOUR/tattour-client/assets/81505421/321caf36-c0f4-4f07-a381-51cc7ca8b049
> List page/#27 bottom sheet publishing

- src/components/List/FilterBottom.tsx
- src/components/List/TattooList.tsx
resolved #98 
- 노가다 이슈
- 그 외 Footer 버튼이 BottomSheet 껐다가 다시 켰을 때 비활성화되지 않고, 계속 활성화되어있던 이슈가 있었는데, useEffect 사용해서 해결했습니다! 
https://github.com/TEAM-TATTOUR/tattour-client/assets/81505421/e4f3a54c-1fc7-40e8-8a9a-aca37f87aa14
> style: 체크 위치 이슈 수정

- src/Router.tsx
- src/components/Custom/NoDesgin/CustomImg.tsx
- src/pages/Custom/NoDesign/CustomImgPage.tsx
resolved #17
```ts
...
<St.ImgAttachContainer>
<input id='img-input' type='file' accept='image/png' />
<St.ImgAttachArea>
<p>도안 이미지를 첨부해주세요</p>
</St.ImgAttachArea>
<label htmlFor='img-input'>
<St.ImgAttachBtn>
<IcPhoto />
<span>사진 첨부하기</span>
</St.ImgAttachBtn>
</label>
</St.ImgAttachContainer>
...
```
- button에 flex를 줘도 되는가 ? => 됨
- button 안에 div 되는가? => 안됨 BUT span은 됨
근데? 알고 보니까 label 처리 해줘야 대서 걍 div로 함 ㅋ
https://github.com/TEAM-TATTOUR/tattour-client/assets/77691829/4f9cd1be-8169-4f22-9ae1-c19adbe4b0ee
> [CustomImgPage] 그려둔 이미지 도안 첨부 UI 구현

- src/common/ProgressBar.tsx
- src/components/Header.tsx
resolved #63 
<br />
1. <progress> 태그를 활용해서 구현했습니다.
2. value: 전체 페이지에 비례하는 현재 단계
3. max: 전체 페이지 수
```
<St.ProgressBarWrapper>
<progress value={curStep} max={maxStep}></progress>
</St.ProgressBarWrapper>
```
4. props로 value와 max를 넘겨주면 재사용할 수 있습니다.
```
<ProgressBar curStep={2} maxStep={5} />
```
<br />
> [Common] progress bar 구현

- src/components/Custom/NoDesgin/CustomImg.tsx
- src/components/Custom/NoDesgin/CustomImgAttach.tsx
- src/components/Custom/NoDesgin/CustomImgHeader.tsx
resolved #43 
<br/>
```ts
{previewURL ? (
<St.ImgPreviewConatiner>
<St.ImgPreviewDelBtn type='button' onClick={handleClickImgPreviewDelBtn}>
<IcCancelDark />
</St.ImgPreviewDelBtn>
<St.ImgPreviewArea>
</St.ImgPreviewArea>
</St.ImgPreviewConatiner>
) : (
<St.ImgAttachArea>
<p>도안 이미지를 첨부해주세요</p>
</St.ImgAttachArea>
)}
```
* fileReader로 업로드 한 이미지의 base64 string type URL을 생성함
* previewURL이 있을 시 보여줌
```ts
const handleClickImgPreviewDelBtn = () => {
setPreivewURL('');
};
```
* 삭제 버튼 누르면 previewURL을 빈 스트링으로 만들어 줘서 미리보기 삭제 구현
<br/>
- 동일 이미지를 다시 첨부 했을 때 첨부가 안되는 오류 발생 -> e.target.value = ""로 초기화 시켜 해결함
<br/>
https://github.com/TEAM-TATTOUR/tattour-client/assets/77691829/344417a7-1dc5-4570-8125-79124da8cd24
=> png 파일만 선택 가능
- [동일 파일 업로드 불가능 …
> [CustomImgPage] 이미 그려둔 도안 이미지 미리보기 및 삭제 구현

- src/components/Order/OrderFooter.tsx
- src/pages/Login/OrderPage.tsx
resolved #41 
- 단순 퍼블리싱
- Header -> 아이콘과 제목만 설정해줌
- Footer -> OrderFooter 컴포넌트 구현함 (navigate 제외) 
https://github.com/TEAM-TATTOUR/tattour-client/assets/81505421/3e01bded-eac2-4e04-b191-188b6ce79334
> Order page/#41 wrap page layout

- src/components/Register/ErrorMessage.tsx
- src/components/Register/InputCertificationForm.tsx
- src/components/Register/RegisterName.tsx
- src/components/Register/RegisterPhoneNumForm.tsx
- src/components/Register/Timer.tsx
- src/utils/sliceMaxLength.ts
resolved #127 
- 인증번호 제한 시간 만료 시 뜨는 뷰를 구현했습니다.
- `isTimeout` 상태를 만들어서 해당 상태가 true일 경우에만 스타일이 적용되도록 했습니다.
- 시간이 만료되면 인증번호 작성 폼이 비활성화 처리되도록 구현했습니다.
<br />
```
<Timer isCorrect={isCorrect} isTimeout={isTimeout} setIsTimeout={setIsTimeout} />
<St.AuthTimer $isTimeout={isTimeout}>
{isTimeout ? '시간 만료' : `${minutes} : ${second}`}
</St.AuthTimer>
```
```
{(isError || isTimeout) && <ErrorMessage isTimeout={isTimeout} />}
<St.NotificationWrapper>
<St.Notification>{isTimeout ? '재인증 버튼을 눌러 다시 인증해주세요.' : '인증번호가 잘못되었어요.'}</St.Notification>
</St.NotificationWrapper>
```
<br />
- sliceMaxLength()의 인자로 inputType을 받아와서 입력받을 수 있는 타입을 제한했습니다.
- 타입 제한에 `정규식`과 `switch-case`를 활용했습니다.
<br />
```
switch (inputType) {
case 'onlyNum':
e.target.value = e.target.value.replace(/[^0-9]/g, ''); …
```
> [LoginPage] 인증번호 제한시간 만료 시 뜨는 뷰 구현

- src/common/Modal/EscapeModal/EscapeModal.tsx
- src/common/Modal/EscapeModal/EscapeModalForm.tsx
- src/components/Header.tsx
- src/pages/MainPage.tsx
- src/utils/BackBtn.tsx
- src/utils/CancelBtn.tsx
resolved #106 
- `뒤로가기` 컴포넌트
<br />
```
const handleClickBack = () => {
navigate(-1);
};
```
- `취소하기` 컴포넌트
- targetModel을 props로 넘겨주었습니다.
- `EscapeModal.tsx`에서 모달에 필요한 내용을 채워주면 됩니다.
<br />
```
// MainPage.tsx
<CancelBtn
modalOn={modalOn}
setModalOn={setModalOn}
targetModal={<EscapeModal setModalOn={setModalOn} />}
/>
```
> [Common] header 공통 컴포넌트 구현 (뒤로 가기, 취소하기)

- src/Router.tsx
- src/components/PointCharge/AccountCopy.tsx
- src/components/PointCharge/Transfer.tsx
- src/components/PointCharge/TransferMain.tsx
- src/components/PointCharge/TransferPolicy.tsx
- src/pages/pointCharge/TransferPage.tsx
resolved #49
- 단순 퍼블리싱입니다 간단히 구조만 봐주세요
- 예비포인트 정책 동의는 리소스 아끼기 위해 숭이가 구현한 부분을 참고했습니다
- 계좌 번호 복사 부분은 복사하기 기능이 붙어 컴포넌트로 따로 빼줬습니다
- x
> [TransferPage] 계좌 송금 페이지 UI 구현

- src/components/Order/PaymentInfo.tsx
resolved #117 
- 서버 측에서 남는 포인트/부족한 포인트 구분 없이 result_price, is_lack 를 준다고 함 
- 따라서 저도 is_lack의 여부에 따라 조건부 렌더링 되도록 구현했습니다. 
https://github.com/TEAM-TATTOUR/tattour-client/assets/81505421/01029a3e-8446-434f-a04c-154494489ff0
> [OrderPage] 포인트 부족 뷰 조건부 렌더링

- src/common/BigScrollContainer.tsx
- src/common/SmallScrollContainer.tsx
- src/components/Header.tsx
- src/components/MyTattoo/MyCustom.tsx
- src/components/MyTattoo/MyCustomItem.tsx
- src/components/MyTattoo/MyLike.tsx
- src/components/MyTattoo/MyLikeItem.tsx
- src/components/MyTattoo/MySave.tsx
- src/components/MyTattoo/MySaveItem.tsx
- src/pages/MyTattoo.tsx
resolved #12 
```tsx
const SmallScrollContainer = ({
title,
children,
}: {
title: string;
children: React.ReactNode;
}) => {
return (
<St.SmallScrollWrapper>
<header>
<St.SmallScrollHeaderTitle>{title}</St.SmallScrollHeaderTitle>
</header>
<St.SmallScrollItemWrapper>
<ScrollContainer vertical={false} className='scroll-container'>
{children}
</ScrollContainer>
</St.SmallScrollItemWrapper>
</St.SmallScrollWrapper>
);
};
```
title로 Scroll Container의 메인 타이틀 작성.
children으로 해당 컴포넌트가 담을 아이템을 받아 구성.
BigScrollContainer는 HotCustom에 주로 사용.
SmallScrillContainer는 비슷한 제품, 찜하기에 사용.
> My tattoo/#12 mytattoo page UI

- src/common/PreventAccess/PreventAccess.tsx
- src/constants/PreventAccessInfo.ts
- src/pages/Error/ErrorPage.tsx
- src/pages/Expiration/ExpirationPage.tsx
resolved #155 
- 각 페이지에 들어갈 내용은 상수로 관리
```
export const TITLE = ['정보를 불러올 수 없어요', '세션이 만료되었어요'];
export const BTN_CONTENTS = ['다시 불러오기', '홈으로 돌아가기']
```
- 공통 컴포넌트 구현
```
<St.ContentsWrapper>
<IcError />
<St.Title>{title}</St.Title>
<St.Button onClick={handleClickButton}>{btn_contents}</St.Button>
</St.ContentsWrapper>
```
- `isError`로 에러/ 만료 페이지 구분 -> 버튼 기능 구현
```
const handleClickButton = () => {
isError ? window.location.reload() : navigate('/');
};
```
- `새로고침`되는 것 보세용
https://github.com/TEAM-TATTOUR/tattour-client/assets/80264647/d867eb90-09fa-4173-8812-3de489d199c0
https://github.com/TEAM-TATTOUR/tattour-client/assets/80264647/6cd23058-2c81-4ddf-9989-414873458cdf
> [Common] 에러, 만료 페이지 퍼블리싱

- src/components/Header.tsx
- src/components/PointCharge/Charge.tsx
- src/components/PointCharge/PointChargeFooter.tsx
- src/pages/PointCharge/ChargePage.tsx
resolved #62
```ts
const ChargePage = () => {
const [isActiveNext, setIsActiveNext] = useState(false);
const renderChargePageHeader = () => {
return (
<Header
leftSection={<St.BlankSection></St.BlankSection>}
title='포인트 충전'
rightSection={<IcCancelDark onClick={() => navigate(-1)} />}
progressBar={<ProgressBar curStep={1} maxStep={2} />}
/>
);
};
return (
<PageLayout
renderHeader={renderChargePageHeader}
footer={<PointChargeFooter isActiveNext={isActiveNext} />}
>
<Charge setIsActiveNext={setIsActiveNext} />
</PageLayout>
);
};
```
isActiveNext, setIsActiveNext state props로 넘겨 줘서 처리
- x
https://github.com/TEAM-TATTOUR/tattour-client/assets/77691829/cec516bb-014e-4de9-ab80-3cb104a5581e
> [ChargePage] 포인트 충전 뷰 레이아웃 + 버튼 비활성화 구현

- src/components/Detail/DetailCarousel.tsx
- src/components/Detail/DetailFooter.tsx
- src/pages/DetailPage.tsx
resolved #226 
- custom 라벨링 조건부 렌더링
- DetailPage에서 서버를 통해 받아오는 isCustom state를 DetailCarousel로 전달
- 전달된 state에 따라 라벨 조건부 렌더링 
- Detail 구매하기/충전하기 navigation
- Footer의 handleClickButton에서 충전하기/구매하기에 따라 navigate 시켜줌
- 전달해야할 state가 있다고 해서 나중에 추가 예정 
- 뒤로가기 버튼 
- <Ic어쩌구/> 에서 유틸 붙어있는 <BackBtn/> 컴포넌트로 바꿔줌
> [Detail Page] 모든 navigation

- src/components/MainPage/MainHeaderButton.tsx
resolved #208 
```
const MainHeaderButton = ({ setIsSideMenuOpen, light }: MainHeaderButtonProps) => {
const handleClickNavButton = () => {
setIsSideMenuOpen(true);
};
const handleClickSearchButton = () => {
navigate('/search');
};
return (
<St.ButtonWrapper>
<St.SearchButton type='button' onClick={handleClickSearchButton}>
{light ? <IcSearchLight /> : <IcSearchDark />}
</St.SearchButton>
<St.NavButton type='button' onClick={handleClickNavButton}>
{light ? <IcMenuLight /> : <IcMenuDark />}
</St.NavButton>
</St.ButtonWrapper>
);
};
```
클릭 이벤트를 추가했습니다.
> [SearchPage] mainPage 아이콘 navigate 연결

- src/components/Custom/SelectCustom.tsx
- src/components/Custom/SelectCustomPolicy.tsx
- src/pages/Custom/SelectPage.tsx
resolved #231 
- se 사이즈 맞춰서 뷰 수정 => 정책 영역은 하단 고정 되고, se보다 큰 사이즈 뷰에서는 상황 선택 버튼이 중앙 정렬 될 수 있도록 구현
```ts
const St = {
SelectWrapper: styled.section`
display: flex;
flex-direction: column;
justify-content: center;
padding: 0 2.75rem;
width: 100%;
height: calc(
100dvh - 24.8rem
); //탭 바 제외 높이 - (헤더 영역 + 정책 영역 + cta 푸터 영역 높이 값)
`,
```
* 탭바 제외한 높이 값을 구해주는 dvh 단위 사용 , 헤더, 정책 영역, cta 푸터 영역 높이 값을 빼서 구현
-정렬 문제 때문에 375사이즈 맞춰서 뷰 짰음 => QA 때 같이 맞춰보고 수정 필요
- x
> [SelectPage] 🚨 최소 사이즈 맞춰서 뷰 수정

- src/components/Custom/HaveDesign/SelectKeyword.tsx
- src/pages/Custom/HaveDesign/SelectKeywordPage.tsx
resolved #251 
- 키워드 선택하면 길이가 변경되면서 밀려서 키워드 배치가 달라지는 문제 해결 완료
- 최소 1개의 버튼을 선택해야만 다음 버튼 활성화되도록 수정
- 라우터 설정 반영
- 클릭하면 너비가 달라지다 보니 배치가 달라져서 클릭했을 때의 너비를 기준으로 너비값을 수정해줬습니다.
- 자꾸 개발자도구 켜서 실행하면 작동이 제대로 안 됐었는데, 
이 화살표 아이콘을 파란색으로 켜놔야 되는 거였습니다..!
https://github.com/TEAM-TATTOUR/tattour-client/assets/92876819/704ece97-9be8-4a3e-bfdf-bd9594e5e958
- [개발자도구 paused in debugger 해결방법](https://velog.io/@songjy377/%ED%81%AC%EB%A1%AC-paused-in-debugger-%ED%95%B4%EA%B2%B0%EB%B0%A9%EB%B2%95)
> [SelectKeywordPage] 클릭시 모양 바뀌는 문제 해결 및 개수 따른 버튼 활성화 적용

- src/common/Footer/NextFooter.tsx
- src/components/Custom/Common/CustomSelectSize.tsx
- src/components/Custom/NoDesgin/CustomImg.tsx
- src/components/Custom/NoDesgin/CustomImgAttach.tsx
- src/components/Custom/NoDesign/CustomRequset.tsx
- src/page/Custom/Common/CustomSizePage.tsx
- src/page/Custom/NoDesign/CustomImgPage.tsx
- src/page/Custom/NoDesign/CustomRequestPage.tsx
- src/page/Custom/PricePage.tsx
resolved #347
- 다음 페이지로 navigate 시 state 넘기기
```ts
//CustomImgPage 예시
...
const haveDesign = location.state ? location.state.haveDesgin : null;
const prevCustomInfo = location.state ? location.state.customInfo : null;
//state에서 필요 값 가져오고
...
const customInfo = {
...prevCustomInfo,
viewCount: CUSTOM_VIEW_COUNT,
};
//해당 페이지에서 가져와서 넘겨줘야 하는 값을 스프레드 문법으로 update
...
```
* 신청서 플로우대로가 아닌 url로 접근하여 중간 페이지에서 haveDesign(상황 선택)에 대한 값이 없는 경우 onboarding으로 navigate
```ts
if (!location.state) navigate('/onboarding');
}, [location.state, navigate]);
//useEffect로 확인 후 navigate
```
- 에러 핸들링이 어려웠습니다 플로우가 복잡해 예기치 않은 상황이 많이 발생하는듯 합니다
- 아직 state에 있는 값을 읽어와 화면에 뿌려오는건 구현 중입니다 해당 pr에 추가로 커밋하겠습니다
> [Custom] custom page navigate 시 state로 필요 한 값 넘기기

- src/common/Header/BackBtn.tsx
- src/common/Modal/EscapeModal/EscapeModalForm.tsx
- src/components/Register/RegisterNameFooter.tsx
- src/components/Register/RegisterPhoneNum.tsx
- src/components/Register/RegisterPhoneNumForm.tsx
- src/page/Login/LoginPage.tsx
resolved #466 
- BackBtn.tsx 코드 수정
- 다시 수정한 코드로 첨부합니당!! 
- step을 사용하는 경우에는 props로 step, setStep 넘겨주면 됩니당
- step을 사용하지 않는 경우 props로 아무것도 안넘겨주면 됩니당
```
interface BackBtnProps {
step?: number;
setStep?: React.Dispatch<SetStateAction<number>>;
}
const BackBtn = ({ step, setStep }: BackBtnProps) => {
const handleClickBack = () => {
// 여기!!!!!
step && setStep ? setStep(step - 1) : navigate(-1);
};
return <IcBackDark onClick={handleClickBack} />;
};
```
- `<` 아이콘을 사용하지만, 독단적인 기능을 하는 경우에는 공통 컴포넌트를 사용하지 않도록 구현
```
const renderRegisterNamePageHeader = () => {
return (
<Header
leftSection={<St.BlankSection></St.BlankSection>}
title='회원가입'
rightSection={
// 여기
<IcCancelDark
onClick={() => {
navigate('/login');
setStep(0);
}}
/>
} …
```
> [LoginPage] 페이지 병합 2차 리팩토링

- src/components/Register/RegisterPhoneNumForm.tsx
- src/components/Register/Timer.tsx
- src/libs/reducers/registerReducer.ts
closed #458  
- **`React.memo`**
- 부모 컴포넌트의 값이 변했을 때, 자식 컴포넌트에 발생할 불필요한 리렌더링을 방지하기 위해 사용
- React.memo로 감싼 컴포넌트는 이전에 전달된 props와 현재의 props를 비교하여 변경이 있을 경우에만 리렌더링하기 때문에 렌더링 최적화 가능
- Timer 컴포넌트 전체를 memo로 감싸줌
<br />
- **`useRef`**
- setState는 값이 변하면 리렌더링이 되지만, useRef는 current 값이 변하더라도 리렌더링 되지 않기 때문에 렌더링 최적화를 할 수 있음
```
// Timer.tsx
const timer = useRef(0);
// setInterval: 두 번째 인자(시간(ms))를 간격으로 첫 번째 인자(코드) 실행
timer.current = setInterval(() => {
// 1초씩 감소
dispatch({ type: 'SET_LEFT_TIME', payload: INTERVAL });
}, INTERVAL);
if (timerState.leftTime <= 0) {
// timer 반복 중단
clearInterval(timer.current);
setIsTimeout(true);
}
return () => {
clearInterval(timer.current);
};
}, [timerState.leftTime, setIsTimeout]);
```
<br />
- 타이머 초기화 안되는 이슈 해결
- reducer에 전화번호 …
> [LoginPage] 타이머 성능 개선

- src/components/PointCharge/Charge.tsx
- 충전 금액을 0원 입력 혹은 입력 후 지우기로 미입력 해도 넘어가서 0원 충전 요청 되는 경우 예외처리
- 디자인 담당자와 상의 후 0원 입력 시에는 '1,000원 이상부터 충전이 가능해요' 메시지 띄워주기로 함
- 0원 입력시 경고 메시지를 다르게 띄워주기 위해서 즉, 0원인 예외 상황을 인지하기 위해 `isZeroWarning`이라는 플래그 만들어 사용
```ts
if (removedCommaValue === 0) {
//0원이면 경고 메시지
setIsZeroWarning(true);
setIsWarning(true);
setIsActiveNext(false);
} else if (removedCommaValue % 1000 === 0) {
//1000원 단위인지 확인
setIsZeroWarning(false);
setIsWarning(false);
setIsActiveNext(true);
} else {
//0원이 아닌데, 1000원 단위가 아닐 때 경고 메시지
setIsZeroWarning(false);
setIsWarning(true);
setIsActiveNext(false);
}
};
const ERR_MSG_CONTENT = isZeroWarning
? '1,000원 이상부터 충전이 가능해요'
: '1,000원 단위 충전만 가능해요';
```
- x
https://github.com/TEAM-TATTOUR/tattour-client/assets/77691829/eb0e29c1-f663-44e6-b189-9dc7bdd70ede
> [ChargePage] 충전액 0원일 때도 다음 cta 비활성화되도록 수정

- src/components/List/FilterBottom.tsx
- src/components/List/TattooList.tsx
- src/components/Order/DeliveryInfo.tsx
- src/page/ListPage.tsx
- src/page/Order/CompletePage.tsx
- src/page/Order/OrderPage.tsx
resolved #474 
- 버튼 클릭 시, type을 넘겨줘서 isSheetOpen <- type 값에 따라 
- onTap, onClose 등 함수화해서 데이터 간소화 (property에서 제외) 
> 그.. 리팩토링을 하나의 이슈로 파서.. 많은 태스크, 커밋을 한번에 묶은 바람에.. 자잘한 수정 사항 외에 굵직 굵직한 태스크만 리팩토링 실행한 과정에 따라 러프하게 정리했습니다 
- 기존 : `sticky`로 고정 → 붕붕 뜸
- 내가 나열한 컴포넌트를 감싸는 의문의 div가 있음 이 div가 화면세로를 꽉 채우지 않고, 애매하게 채우며, sticky footer는 그 div의 최하단에 위치해있기 때문에 함께 붕붕 뜨게 됨
- **어디서 온 div인가!!!!  pageLayout발인 것 같은데, 그렇다면 다른 페이지 애들이 멀쩡한 이유는? 혹시 completePage가 내부 콘텐츠가 얼마 없어서 그런걸까?**
- `fixed`로 변경하면?
- 최하단에 고정은 잘 됨 (붕붕 뜨는 문제 해결)
- 데스크탑뷰로 봤을 때, min width가 먹히지 않아 버튼이 퍼져버리고
- 콘텐츠가 화면을 가득 채우지 않는(스크롤X) completePage에서는 문제가 없지만, 다른 페이지 푸터를 fixed로 박아보면 내부에 있는 콘텐츠들과 무관하게 화면의 최하단에 박히기 때문에, **콘텐츠의 아래부분이 Footer에 가려져버리는 문제**가 발생한다.
- `absolute`로 변경하면?
- 최하단에 고정은 되지만, **이상한 1px**이 생겨버린다. (하단 사진 참고)
- <img width="472" …
> List page/#474 2nd refactor

- src/components/Custom/NoDesign/Img/CustomImgAttach.tsx
- src/components/Custom/NoDesign/Img/CustomImgLayout.tsx
- src/components/Custom/NoDesign/Request/CustomRequestLayout.tsx
resolved #481 
- 커스텀 도안 이미지 통신 형식이 fileBlob -> FileList 자체로 바뀌면서 급하게 코드를 수정하느라 동일 이미지를 재첨부시 첨부가 안되는 문제를 해결 못했었습니다
- 동일 이미지를 다시 첨부시, ChageEvent에서 인식되지 못하는 문제가 있어 동일 이미지는 연속해서 첨부가 안돼 문제가 발생했습니다.
- 아마 지민언니 플로우에서도 같이 발생했던 문제라 참고하면 좋을것 같습니다 ~!
- 해결한 코드 
-> DataTransfer 객체가 반환하는 빈 FileList로 input이 들고 있는 FileList의 file들을 교체시킴 (빈 FileList로 초기화 시킴)
```ts
const handleChangeImgAttach = (e: React.ChangeEvent<HTMLInputElement>) => {
const { files } = e.target;
if (!files) return; // early return
const fileBlob = files; // 서버 통신 시 보낼 타입
setCustomImages(fileBlob);
const reader = new FileReader();
reader.readAsDataURL(fileBlob[0]);
reader.onloadend = () => {
setPreviewURL(reader.result as string);
}; // FileReader로 이미지 미리보기 구현
// 🚨 같은 파일을 올리면 change 이벤트 인지 못해서 여기서 초기화
const dataTransfer = new …
```
> [Custom:NoDesign] 동일 이미지 재첨부 안되는 문제 해결

- src/common/HotCustom.tsx
- src/components/List/TattooList.tsx
- src/page/ListPage.tsx
- src/page/MainPage.tsx
resolved #491 
1. 화살표 버튼 삭제 
- HotCustom 컴포넌트에 prop 추가 isList
- isList : 메인화면에서 왔으면 false, ListPage에서 왔으면 true
- isList에 따라 헤더 화살표 조건부 렌더링
2. HOT CUSTOM 리스트 양옆 여백 조정 
- 변경 전 : 스크롤과 부관하게 좌우 여백 있음
- 변경
- 최상단 section 자체에 있는 margin/padding 들 삭제
- 최상단 section 삭제했더니 HOT CUSTOM 헤더 margin도 사라져서 별도로 넣어줌
- list 내용물 양옆에 padding 추가 (스크롤의 시작과 끝에 여백 생기도록)
3. 각종 글자 볼드 변경 
- 핫커스텀 ‘원’ 볼드 빼고
- 전체 개수 볼드 추가
> [List Page] 2차 QA

- src/common/CustomScrollContainer.tsx
- src/common/SmallTattooCard.tsx
- src/components/Detail/DetailFooter.tsx
- src/components/Detail/DetailInfo.tsx
- src/libs/hooks/detail/useGetRelated.tsx
- src/page/DetailPage.tsx
resolved #492 
- 각종 폰트, 굵기, 색상, 정렬, 여백 수정 모두 완료 ✅
- 회색 박스 하단 영역 차이 -> 반영 안함 ❌
현재 우리 서비스는 상품당 사진이 한장 뿐이라서 하단 indicator(pagination 동글뱅이)가 자동으로 빠짐. 그래서 indicator 자리만큼 하단 회색 영역의 높이가 줄어든것. 근데 indicator 없는 경우에도(한 장인 경우에도) 회색 영역 높이를 맞추면 해당 이미지처럼 위아래 간격이 안맞아서 사진이 가운데 정렬이 안된 것처럼 붕붕 떠버림! -> 이 내용 규태한테 전달했고 디팟과 논의해본다고 함 
- 더보기 기능 삭제하기로 해서 삭제함 ✅
- 비슷한 제품 추천에서 제품 클릭해서 이동할 경우, 뒤로가기를 눌렀을 때 이전 제품 상세페이지로 이동하는 문제 -> 상세페이지가 아닌 **목록 페이지로 이동**해야함 (계속해서 비슷한추천제품 타고 들어갈 경우 뒤로가기 depth가 무한히 깊어지기 때문에) 
- BackBtn에 `navigate('/list')` 달아서 해결 
- 추천아이템 하나 눌렀을 때 비슷한 추천 리스트가 반영(리렌더링)이 안됨
- relatedResponse를 mapping 해서 제품카드를 만드니까 **서버에서 불러온 relatedResponse 값**이 제대로 update되지 않는 것으로 보임
- **useGetRelated 통신**이 잘 안된 것으로 보임
- 비슷한 제품 추천 리스트 외에 **제품의 상세 정보는 잘 렌더링** 되는데, 둘이 똑같은 시점에 똑같은 방식으로 서버통신을 하고 있다.
- ➡️ 따라서 세부 정보를 불러오는 커스텀훅인 …
> [DetailPage] 2차 QA

- src/components/Order/DeliveryInfo.tsx
- src/components/Order/PaymentInfo.tsx
- src/components/Order/RefundInfo.tsx
- src/libs/hooks/order/useGetOrdersheet.tsx
- src/page/Order/OrderPage.tsx
resolved #493 
아래거 이슈 하나 외엔 다 단순 css 수정입니다! 
- **서버에서 불러온 유저정보로 input 기본값 세팅**
- 처음엔 input과 phone의 state값의 기본값으로 바로 서버에서 받은 값들을 넣어줬는데, 최초에 response가 undefined로 불러와질때 때문에 기본값이 빈 텍스트로 채워져버리는 문제 봉착.
- 따라서 response가 update될때 새로 state를 set하도록 아래와 같이 useEffect로 구현함.
```jsx
setInput(response?.userProfileInfo.name);
setPhone(response?.userProfileInfo.phoneNumber);
}, [response]);
```
- input에는 서버에서 받아온 유저 정보가 성공적으로 박혔지만, 갑자기 아래와 같은 Warning 발생
→ 찾아보니 input의 value에 undefined type이 가능한 경우가 오면 안된다고 !
→ 구체적인 코드에서는 **setter 내부의 옵셔널체이닝** 때문에 발생한 Warning이었다. 
➡️ 따라서 옵셔널 체이닝을 없애되, response가 undefined일 경우에 발생하는 에러를 막기 위해 useEffect 최상단에 빠른 return문을 추가해 주어 해결하였다. 
```jsx
if (!response) return;  // 여기!
setInput(response.userProfileInfo.name); …
```
> [OrderPage] 2차 QA

- src/Router.tsx
- src/components/Custom/Common/PriceLayout.tsx
- src/components/Custom/Common/Receipt/ReceiptDetail.tsx
- src/components/Custom/Common/Receipt/ReceiptLayout.tsx
- src/components/Custom/Common/Size/CustomSizeLayout.tsx
- src/components/Custom/CountPrice.tsx
- src/components/Custom/NoDesign/NoDesignFooter.tsx
- src/components/Custom/PriceFooter.tsx
- src/page/Custom/Common/CommonCustomPage.tsx
- src/page/Custom/NoDesign/NoDesignCustomPage.tsx
- src/types/customInfoType.ts
resolved #497 
* 아직 통합 안된 앞 플로우라서 /custom -> /haveDesign or /noDesign으로 navigate 됨. 그러나 size, customId 정보들은 /custom에서 받아와야 하므로 여기서는 navigate 시 state 전달 해주는걸 사용했습니다
* 이 과정에서 앞 pr에서 수정한 '/custom'관련 컴포넌트들에도 props, navigate 수정이 있었습니다
```ts
//noDesignFooter.tsx
const handleClickFooter = () => {
{
navigateURL &&
navigate(navigateURL, {
state: {
//여기서 navigate 시 필요한 값들 state로 넘겨주고
size: size,
customId: customId,
},
});
isActiveNext && setStep((prev) => prev + 1);
}
```
```ts
//NoDesignCustomPage.tsx
const location = useLocation();
// 앞에 size + customId 통합해놓은거에서 navigate로 내기 때문에 우선 navigate state로 관련 정보 불러옴
const size = location.state ? location.state.size : null;
const customId = location.state ? location.state.customId : null;
```
<hr/>
<br/>
```ts
//noDesignCustomPage.tsx
//통합 페이지에서 patch에 보낼 …
```
> [Custom: noDesign] price + receipt 페이지들까지 noDesign 통합 페이지에 우선 통합

- src/common/ToastMessage/Toast.tsx
- src/components/PointCharge/AccountCopy.tsx
resolved #505 
- 크게 수정한 내용없으니 가볍게 봐주시면 될 듯 합니당
- 아래 이슈는 `common > ToastMessage > Toast.tsx` 에 `z-index: 1`을 줘서 해결했습니다!
> [toast message] QA 내용 반영

- src/Router.tsx
- src/common/Modal/ChargePointModal/ChargePointCompleteModal.tsx
- src/common/Modal/ChargePointModal/ChargePointModalForm.tsx
- src/common/Modal/CheckModal/CheckModal.tsx
- src/common/Modal/CheckModal/CheckModalForm.tsx
- src/common/Modal/EscapeModal/ChargePointEscapeModal.tsx
- src/common/Modal/EscapeModal/EscapeModalForm.tsx
- src/common/Modal/EscapeModal/LoginEscapeModal.tsx
- src/common/Modal/WelcomeModal/WelcomeModalForm.tsx
- src/common/PreventAccess/PreventAccess.tsx
- src/components/PointCharge/PointTransferFooter.tsx
- src/components/Register/RegisterPhoneNumForm.tsx
- src/libs/hooks/useKakaoLogin.tsx
resolved #504 
- 아래 명시하지 않은 이슈는 단순 css 수정으로 해결했습니다! (코드 한 번씩 확인 부탁드려용)
- 에러페이지 라우팅 `/error` 로 접근 가능
<br />
- 모달 내용 줄바꿈 애매하게 되는 이슈
- subTitle을 2개로 나눈 뒤, css 수정하여 해결
```tsx
// common > Modal > CheckModal > CheckModal.tsx
subTitle={'정확하게 송금하지 않을 시'}
subTitle_2={'추후에 주문이 취소될 수 있어요'}
```
```tsx
// common > Modal > CheckModal > CheckModalForm.tsx
<St.ModalSubTitle>{subTitle}</St.ModalSubTitle>
<St.ModalSubTitle>{subTitle_2}</St.ModalSubTitle>
```
<br />
- 모달 양 옆 마진 넓어보이는 이슈
- 모달 크기를 고정해서 발생하는 이슈로, 오히려 크기가 아닌 양 옆 마진을 고정할 경우 모달 크기가 화면 max-width 보다 커지는 이슈가 발생하여 디자인과 상의 후 기존 방식(모달 크기 고정) 그대로 가져가기로 함
<br />
- `X` 아이콘 빠져있는 이슈
- 모달을 컨트롤할 수 있는 `setIsOpenCompletModal`을 props로 전달
```tsx
// ChargePointCompleteModal.tsx
<ChargePointCompleteModal
setModalOn={setIsOpenCompletModal} …
```
> [modal] qa 내용 반영

- src/common/Modal/WelcomeModal/WelcomeModalForm.tsx
Closed #504 
- 하단 버튼과 모달 내용을 전부 포함하는 영역(`ModalContent`)이 흰 배경을 가지고 있음
- `예상 원인`: 이로 인해 버튼 사이드 간격이 조금이라도 맞지 않을 경우 뒷 배경이 보이게 된다고 파악
- 버튼과 모달 내용을 모두 포함하는 영역(`ModalContent`)은 배경 색을 갖게 않게 수정
- 모달 내용을 감싸는 영역(`Contents`)을 하나 추가하여 이 부분이 흰 배경을 갖도록 함
```
<St.ModalContent>
<St.Contents>
<St.ModalTitleWrapper>
<IcCancelDark onClick={onClose} />
<St.ModalTitle>{title}</St.ModalTitle>
</St.ModalTitleWrapper>
<ImgPointCoupon />
</St.Contents>
<St.BtnWrapper>
<St.ContinueBtn onClick={handleClickContinueBtn}>{continueBtn}</St.ContinueBtn>
</St.BtnWrapper>
</St.ModalContent>
```
- 원인 파악을 하는 과정이 지끈지끈 했지만 리댜숭의 도움으로 예상되는 원인을 찾았슴돠 (리댜숭 감솨...🖤)
- 코드를 수정함에 따라 해당 이슈가 해결된 듯 하지만, 배포 후 모바일로 봐야 정확히 알 수 있을 듯 합니다
> [modal] qa 반영 2차 리팩토링

- src/common/SideMenu.tsx
- src/common/SideMenuUserInfo.tsx
- src/common/UserInfoSection.tsx
- src/components/MainPage/MainBanner.tsx
- src/libs/hooks/useGetUserProfile.ts
- src/styles/style.d.ts
- src/styles/theme.ts
resolved #499 
font 사이즈 수정 및 새로운 font 크기 추가 (title_bold_xx ...)
video tag에 object-fit: fill 속성 추가로 사이즈 조정
font 사이즈 수정 및 새로운 font 크기 추가
> Qa morgan/#499 mainpage qa

- src/components/Custom/Common/OnBoardingFooter.tsx
- src/components/Custom/Common/Select/SelectCustomFooter.tsx
- src/libs/hooks/usePostCustomApply.ts
- src/page/Custom/Common/CommonCustomPage.tsx
resolved #571 
- 기존에 포인트 충전 모달에서 이루어지던 커스텀 신청 api ('custom/apply')를 상황 선택 -> 사이즈 선택을 연결해주는 footer로 이동시켰습니다.
- usePostCustomApply 커스텀 훅을 만들어서 연결시켰습니다
```tsx
import { AxiosError, isAxiosError } from 'axios';
import { useEffect, useState } from 'react';
import api from '../api';
import { useNavigate } from 'react-router-dom';
interface CustomApplyResponseData {
customId: number;
}
interface CustomApplyResponse {
data: CustomApplyResponseData;
code: number;
message: string;
}
const usePostCustomApply = (haveDesign: boolean) => {
const [response, setResponse] = useState<CustomApplyResponseData>();
const [error, setError] = useState<AxiosError>();
const [loading, setLoading] = useState(true);
const fetchData = async () => {
try {
const { data } = await …
```
> [SP1/Custom] 커스텀 신청시 포인트 충전 모달 삭제, 커스텀 신청 api 연결

- package.json
- src/common/Modal/EscapeModal/EscapeModalForm.tsx
- src/components/MainPage/MainEventBanner.tsx
- src/libs/hooks/usePostCustomApply.ts
- src/page/Custom/NoDesign/NoDesignCustomPage.tsx
- src/page/MainPage.tsx
- yarn.lock
- close #585 
```shell
...
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-darwin-unknown-arm64.tar.gz
...
```
이렇게 canvas 모듈을 설치하는 과정에서 문제가 발생했는데요! 
찾아보니까 node-gyp라는 Node.js 빌드 도구를 사용해야 한다는데 해당 모듈이 안깔려있길래 추가로 깔아줬고...
macOS에서는 또 이상한 개발자 도구를 설치해야할 수도 있다고 해서 이것저것 다 해보다가 갑자기 install 에러가 사라지는 바람에 얼떨결에(?) 해결이 된 상황입니다 ... (찝찝이슈) 
canvas 모듈이 포함되어있는 fabric 라이브러리 관련해서 좀 찾아봤는데 fabric 라이브러리 자체가 react랑은 잘 맞지 않는 친구인 것 같다는 느낌도... 들었습니다 😱😱😱😱 그래서 만약 지민언니가 커스텀 기능을 리팩토링할 계획이 있다면! 다른 적절한 라이브러리는 없을지 찾아보는 것도 좋은 경험이 될 거 같슴니다!! (물론 canvas 모듈이 더이상 골머리를 썩히지 않는다면 그대로 가도 완전 오케이!!) 
컴포넌트 props는 setStep이 필수로 되어있는데, 호출부에서 setStep을 안넘겨주고 있는 곳이 많았습니다. 
넘겨줘야하는데 누락된건지, 아니면 optional props가 맞는지 모르겠어서 일단 optional 처리 해두었으니 …
> [SP1] build 에러 해결 

- src/components/MyTattoo/MyLike.tsx
- src/libs/hooks/detail/useGetSticker.tsx
- src/libs/hooks/useGetCustomDetail.ts
- src/libs/hooks/useGetLikeSticker.ts
- src/libs/hooks/useKakaoLogin.tsx
- src/page/DetailPage.tsx
- resolved #587 
배포서버 **swagger** 참고하면서 작업했습니다 (개발서버는 로그인부터 500에러가 터져서 일단 배포서버 기준으로 작업했습니다) 
[배포서버 swagger](https://dev.tattour.shop/swagger-ui/index.html#/)
QA 돌리면서 터지는 부분 찾아서 해결했습니다. 현재 배포계(dev)와 연동시키면 `메인-로그인-상세보기-장바구니-구매하기` 플로우는 아무런 이상 없습니다! 다만, api 통신과 무관한 자잘한 QA 사항들은 남아있어서 (어느부분에서 뒤로가기 하면 터진다던가) 이런 부분은 추후 공유드리겠습니다 
QA에서 오류를 뱉지는 않았지만, api hook을 돌면서 swagger와 대조해보는 과정에서 interface에 누락된 프로퍼티가 있는 경우 주석으로 추가해두었습니다. 아래 두 훅 담당자분은 나중에 주석 확인해보시고 불필요한 프로퍼티면 삭제해주세요! 
- useGetCustomDetail
- useKakaoLogin
> [SP1] api 누락된 항목 반영 

- src/components/Custom/HaveDesign/Reference/Canvas.tsx
- src/components/Custom/HaveDesign/Reference/ColorPicker.tsx
- src/components/Custom/HaveDesign/Reference/CustomImageAttach.tsx
- src/components/Custom/HaveDesign/Reference/CustomReference.tsx
- src/components/Custom/HaveDesign/Reference/PaintBottomHeader.tsx
- src/components/Custom/HaveDesign/Reference/PaintBottomSheet.tsx
- 화면 사이즈에 따라 캔버스 사이즈가 달라지도록 수정했습니다. 높이는 고정이고, 너비는 화면의 가로 너비가 넓어지면 넓어지도록 수정했는데 높이도 화면 사이즈에 따라 달라지는 것이 좋을지 고민돼서 의견 부탁드려요! 화면 사이즈가 달라지면 `canvas` 생성할 때 새롭게 넓어진 너비의 캔버스를 생성하는 함수를 추가했습니다.
```typescript
const handleResize = () => {
if (canvasRef.current?.parentElement?.parentElement) {
setContainerWidth(canvasRef.current.parentElement.parentElement.clientWidth);
}
};
```
- 대충 그리기라고 잘못 작성되어 있던 UX 라이팅 수정 완료했습니다.
- 브러시 커스텀 팔레트 배열을 스크롤이 생기지 않도록 `space-between`으로 조정했습니다.
- 기존에 있던 `canvas.dispose()`를 삭제해도 그림 그리기 완료를 누르면 컴포넌트가 unmount됨에 따라 그림이 초기화되어서 해당 코드를 삭제했습니다.
- canvas wrapper의 width에 맞게 canvas가 생성되지 않고, 그림 그릴 수 있는 영역이 더 길게 잡히는 문제가 있었는데, 제가 원하는 상위 컴포넌트의 width를 참조할 수 있도록 수정했고, resize에 맞게 달라져야 해서 `useState`를 추가했습니다.
```typescript …
```
> [SP1] 커스텀 팔레트 정렬 수정, UX 라이팅 수정, 화면 사이즈 변경에 따른 canvas 사이즈 조정 함수 추가

- src/common/SideMenu.tsx
- src/common/SideMenuUserInfo.tsx
- src/styles/style.d.ts
- src/styles/theme.ts
resolved #603 
- 폰트 추가 및 적용
- padding 간격 수정
> [SideMenu] 탭바 QA 반영

- src/components/Register/RegisterPhoneNumForm.tsx
resolved #621 
- 인증번호 요청 버튼이 계속해서 눌리게 되면, 서버 통신도 그만큼 이뤄지기 때문에 인증번호 문자 요금도 계속 청구
- setTimeout과 isDisabled라는 상태를 만들어서 해결했습니다.
- 버튼 클릭 후, 서버 통신이 제대로 이뤄졌다면 setIsDisabled(true) -> 통신이 모두 끝난 이후 setTimeout 실행
- setTimeout 내부 -> setIsDisabled(false)로 바꿔줌.
- 시간을 체크해보니 문자가 오기까지 대략 5초 내외의 시간이 걸림 + 문자가 도착하기 전에 버튼 비활성화가 풀리면 안된다고 판단하여 7초의 시간제한을 줬습니다. (테스트 결과 10초는 너무 길다고 느껴짐)
- 여러 번 버튼 클릭했지만, 비활성화 되어있기 때문에 문자는 하나만 옴 !
https://github.com/TEAM-TATTOUR/tattour-client/assets/80264647/2938d711-88b8-46c4-8a21-28329c72c06f
> [S1]  인증번호 요청 버튼 클릭 시, n초 간 버튼 비활성화

- src/page/DetailPage.tsx
resolved #624 
- 상세페이지 뒤로가기 시 기존에는 무조건 list로 이동시켰는데, 메인뷰orlist 중 이전 페이지로 돌아가는 것으로 수정했습니다 
```tsx
<IcBackDark
onClick={() => {
navigate(-1);  //여기
}}
/>
```
> [S1] 상세페이지 뒤로가기 위치 변경 
